name: Dev actions
run-name: ${{ github.run_id }} ${{ github.actor }} running dev integration

on:
  push:
    branches:
      - devevelop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.11.1'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Greeting
        run: echo "Hello, ${{ github.actor }}"