name: Deploy to github pages
run-name: ${{ github.run_id }} ${{ github.actor }} running deploy(main) to github pages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Set up Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '20.11.1'
        - name: Install dependencies
          run: npm install
        - name: Build
          run: npm run build
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist
